# dirs to fuzzy search
fuzzy_search_dirs:
  #  - "${HOME}/CodeSpace"
  # - "${HOME}/.config"
  # - "${HOME}/.ssh"
  # - "${HOME}/temp"
  - "${HOME}"

# dirs to ignore
# you do not need to give full path
# it will ignore path which INCLUDES string below
fuzzy_search_ignore_dirs:
  # - ".bin"
  # - ".git"
  # - ".cache"
  # - "node_modules"
  # - "bin"
  # - "pkg"
  # - "dist"
  # - "assets"
  # - "image"
  # - "images"
  # - "static"
  # - "data"
  # - "raycast"
  - ".*"

# choose preview
# if use 'preview', you can see content of file, but it will pay some cost of speed
# if not use 'preview', speed can be little faster
fuzzy_search_preview:
  enable: true
  # enable: false

