# dirs to fuzzy search
fuzzy_search_dirs:
  #  - "${HOME}/CodeSpace"
  # - "${HOME}/.config"
  # - "${HOME}/.ssh"
  # - "${HOME}/temp"
  - "${HOME}"

# dirs to ignore
fuzzy_search_ignore_dirs:
  # - "node_modules"
  # - ".git"
  # - "dist"
  # - ".cache"
  # - "from-github"
  # - "assets"
  # - "image"
  # - "images"
  # - "static"
  # - "data"
  # - "raycast"
  # - "obsidian-*"
  # - "zlt-*"
  - ".*"

# choose preview
# if use 'preview', you can see content of file, but it will pay some cost of speed
# if not use 'preview', speed can be little faster
fuzzy_search_preview:
  enable: true
  # enable: false

