# dirs to fuzzy search
search_dirs:
  # - "${HOME}/CodeSpace"
  - "${HOME}"

# dirs to ignore
search_ignore_dirs:
  # - "Downloads"
  # - "Desktop"
  - ".git"
  - ".local"
  - ".m2"
  - ".gradle"
  - ".wns"
  - ".nvm"
  - ".npm"
  - ".nrm"
  - ".red-hat"
  - ".oh-my-zsh"
  - ".github"
  - ".cache"
  - ".cargo"
  - ".rustup"
  - ".vscode"
  - ".vscode-insiders"
  - ".vscode-server-insiders"
  - ".vscode-server"
  - ".vscode-oss"
  - ".vscode-oss-insiders"
  - "lib"
  - "node_modules"
  - "pkg"
  - "bin"
  - "dist"
  - "pkgs"
  - "from-github"
  - "assets"
  - "image"
  - "images"
  - "static"
  - "data"
  - "raycast"
  - "obsidian-*"
  - "zlt-*"
  - "anaconda3"
  - "Applications"
  - "Library"
  - "Movies"
  - "Music"
  - "Pictures"
  - "Public"
  - "Remote"
  - "Zotero"
  - "EVPlayer2_download"


# choose preview
search_preview:
  enable: true
  # enable: false

# choose fuzzy search editor
fuzzy_search_editor: "vim"
#fuzzy_search_editor: "nvim"